// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pfddhpcwwbthnzmmzaps.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBmZGRocGN3d2J0aG56bW16YXBzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1NjA0MjYsImV4cCI6MjA3NDEzNjQyNn0.WKcVemIX6bB0kblM8g_vYr5OVAamhikAtHNoAqG3VKI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});